In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('UDISE_2023-24_Table_2.1.csv')

In [3]:
df.columns = df.columns.str.replace(" ", "_")
df.columns = df.columns.str.replace("-", "_")
df.columns = df.columns.str.lower()
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.options.display.float_format = '{:,.2f}'.format

In [4]:
df.head()

,sl._no.,india/state/ut,total_number_of___schools,total_number_of___enrolments,total_number_of___teachers,percentage_share_of_schools_by_category___primary,percentage_share_of_schools_by_category___upper_primary,percentage_share_of_schools_by_category___secondary,percentage_share_of_schools_by_category___higher_secondary,percentage_share_of_enrolments_by_level____primary_,percentage_share_of_enrolments_by_level____upper_primary_,percentage_share_of_enrolments_by_level___secondary,percentage_share_of_enrolments_by_level___higher_secondary,percentage_share_of_teachers_by_school_category___primary,percentage_share_of_teachers_by_school_category___upper_primary,percentage_share_of_teachers_by_school_category___secondary,percentage_share_of_teachers_by_school_category___higher_secondary
0,1,India,1471891,248045828,9807600,50.00,29.40,9.80,10.80,48.70,25.40,14.90,10.90,24.00,28.60,16.20,31.10
1,2,Andaman and Nicobar Islands,412,72119,5750,50.70,19.20,13.10,17.00,46.10,23.60,15.90,14.40,17.30,16.90,17.50,48.30
2,3,Andhra Pradesh,61373,8741885,338293,61.50,13.50,18.90,6.10,46.10,25.70,16.50,11.60,28.60,14.00,42.70,14.70
3,4,Arunachal Pradesh,3490,323717,24700,48.60,36.80,9.50,5.20,53.70,24.00,13.40,8.90,19.10,42.60,20.60,17.60
4,5,Assam,56630,6922533,342199,66.20,16.70,12.50,4.70,53.40,25.10,14.30,7.20,32.60,20.50,29.10,17.80

In [6]:
df.columns

Index(['sl._no.', 'india/state/ut', 'total_number_of___schools',
       'total_number_of___enrolments', 'total_number_of___teachers',
       'percentage_share_of_schools_by_category___primary',
       'percentage_share_of_schools_by_category___upper_primary',
       'percentage_share_of_schools_by_category___secondary',
       'percentage_share_of_schools_by_category___higher_secondary',
       'percentage_share_of_enrolments_by_level____primary_',
       'percentage_share_of_enrolments_by_level____upper_primary_',
       'percentage_share_of_enrolments_by_level___secondary',
       'percentage_share_of_enrolments_by_level___higher_secondary',
       'percentage_share_of_teachers_by_school_category___primary',
       'percentage_share_of_teachers_by_school_category___upper_primary',
       'percentage_share_of_teachers_by_school_category___secondary',
       'percentage_share_of_teachers_by_school_category___higher_secondary'],
      dtype='str')

In [14]:
df.query("total_number_of___teachers < 50000")

,sl._no.,india/state/ut,total_number_of___schools,total_number_of___enrolments,total_number_of___teachers,percentage_share_of_schools_by_category___primary,percentage_share_of_schools_by_category___upper_primary,percentage_share_of_schools_by_category___secondary,percentage_share_of_schools_by_category___higher_secondary,percentage_share_of_enrolments_by_level____primary_,percentage_share_of_enrolments_by_level____upper_primary_,percentage_share_of_enrolments_by_level___secondary,percentage_share_of_enrolments_by_level___higher_secondary,percentage_share_of_teachers_by_school_category___primary,percentage_share_of_teachers_by_school_category___upper_primary,percentage_share_of_teachers_by_school_category___secondary,percentage_share_of_teachers_by_school_category___higher_secondary
1,2,Andaman and Nicobar Islands,412,72119,5750,50.70,19.20,13.10,17.00,46.10,23.60,15.90,14.40,17.30,16.90,17.50,48.30
3,4,Arunachal Pradesh,3490,323717,24700,48.60,36.80,9.50,5.20,53.70,24.00,13.40,8.90,19.10,42.60,20.60,17.60
6,7,Chandigarh,230,265706,10237,6.10,18.30,30.40,45.20,45.00,23.90,15.30,15.80,2.00,7.50,26.20,64.40
8,9,Dadra and Nagar Haveli and Daman and Diu,432,141282,4995,37.50,40.50,8.80,13.20,50.90,25.10,15.50,8.40,13.20,37.00,10.70,39.10
10,11,Goa,1487,304735,14594,58.00,5.20,28.40,8.40,48.50,23.70,15.10,12.80,20.40,4.40,53.20,22.00
18,19,Ladakh,995,56642,6432,39.40,44.00,11.50,5.10,58.00,20.50,14.00,7.50,14.60,42.60,26.40,16.40
19,20,Lakshadweep,37,12591,911,40.50,24.30,0.00,35.10,51.50,22.10,13.30,13.10,24.90,24.60,0.00,50.50
22,23,Manipur,4646,647434,40921,52.70,20.30,20.80,6.20,55.30,21.70,13.10,9.80,21.60,19.10,36.90,22.40
24,25,Mizoram,3941,293763,23013,37.20,38.90,18.30,5.70,55.90,22.20,13.60,8.30,25.10,46.20,19.30,9.40
25,26,Nagaland,2725,412975,32602,41.80,28.70,21.40,8.10,56.60,21.30,12.90,9.20,20.20,26.10,30.70,22.90
27,28,Puducherry,735,244828,13202,37.10,9.40,25.20,28.30,46.20,23.50,16.00,14.30,14.00,5.90,22.90,57.30
30,31,Sikkim,1254,121395,15489,53.30,25.10,11.50,10.10,50.80,21.30,14.90,13.00,22.80,25.10,19.70,32.40
33,34,Tripura,4923,689408,37661,50.20,25.30,13.60,10.80,48.40,25.20,14.60,11.80,20.50,20.00,21.80,37.60

In [8]:
df[df["total_number_of___schools"] < 10000][[
    "india/state/ut",
    "total_number_of___schools"
]].sort_values("total_number_of___schools", ascending=True)

                              india/state/ut  total_number_of___schools
19                               Lakshadweep                         37
6                                 Chandigarh                        230
1                Andaman and Nicobar Islands                        412
8   Dadra and Nagar Haveli and Daman and Diu                        432
27                                Puducherry                        735
18                                    Ladakh                        995
30                                    Sikkim                       1254
10                                       Goa                       1487
25                                  Nagaland                       2725
3                          Arunachal Pradesh                       3490
24                                   Mizoram                       3941
22                                   Manipur                       4646
33                                   Tripura                       4923
9                                      Delhi                       5497

In [9]:
#top 10 states with most enrolments (have used 11 as India is also there)
df.sort_values(
    by="total_number_of___enrolments",
    ascending=False
)[["india/state/ut", "total_number_of___enrolments"]].head(11)

    india/state/ut  total_number_of___enrolments
0            India                     248045828
34   Uttar Pradesh                      41662794
21     Maharashtra                      21375970
5            Bihar                      21348149
36     West Bengal                      18015525
29       Rajasthan                      16786065
20  Madhya Pradesh                      15361543
31      Tamil Nadu                      12993050
16       Karnataka                      11926303
11         Gujarat                      11496709